{{- if and .Values.launchpad.enabled .Values.launchpad.certmanager.enabled -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-internal-crt-launchpad
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  secretName: {{ .Values.launchpad.tls.internal.secretName }}
  duration: {{ .Values.launchpad.certmanager.duration | quote }}
  renewBefore: {{ .Values.launchpad.certmanager.renewBefore | quote }}
  {{- if or (not .Values.launchpad.certmanager.commonName) (eq (len .Values.launchpad.certmanager.commonName) 0) }} 
  commonName: {{ (include "launchpad.host" .) | quote }}
  dnsNames: 
  - {{ (include "launchpad.host" .) | quote }}
  {{- else }}
  commonName: {{ .Values.launchpad.certmanager.commonName }}
  dnsNames: {{ .Values.launchpad.certmanager.dnsNames }}
  {{- end }}
  issuerRef:
    name: {{ .Values.launchpad.certmanager.issuerRef.name }} 
    kind: ClusterIssuer
{{- end}}
{{- if and .Values.stardog.enabled .Values.stardog.certmanager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-internal-crt-stardog
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  secretName: {{ .Values.stardog.tls.internal.secretName }}
  duration: {{ .Values.stardog.certmanager.duration | quote }}
  renewBefore: {{ .Values.stardog.certmanager.renewBefore | quote }}
  {{- if or (not .Values.stardog.certmanager.commonName) (eq (len .Values.stardog.certmanager.commonName) 0) }}
  commonName: {{ (include "stardog.host" .) | quote }}
  dnsNames:
  - {{ (include "stardog.host" . ) | quote }}
  {{- else }}
  commonName: {{ .Values.stardog.certmanager.commonName }}
  dnsNames: {{ .Values.stardog.certmanager.dnsNames }}
  {{- end }}
  issuerRef:
    name: {{ .Values.stardog.certmanager.issuerRef.name }}
    kind: ClusterIssuer
{{- end}}
