{{ if .Values.launchpad.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stardog.fullname" . }}-launchpad
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app: {{ include "stardog.fullname" . }}-launchpad
  replicas: {{ .Values.launchpad.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "stardog.fullname" . }}-launchpad
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: server
        stardog.com/deployname: {{ .Release.Name }}-launchpad
        stardog.com/resource-type: stardog-apps
      {{- with .Values.launchpad.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.launchpad.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.launchpad.image.username .Values.launchpad.image.password }}
      imagePullSecrets:
          - name: {{ .Release.Name }}-launchpad-image-pull-secret
      {{- end }}
      serviceAccountName: {{ include "launchpad.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.launchpad.securityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-launchpad
          image: {{ .Values.stardog.image.registry }}/{{ .Values.launchpad.image.repository }}:{{ .Values.launchpad.image.tag }}
          imagePullPolicy: {{ .Values.launchpad.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.launchpad.service.port }}
              protocol: TCP
          env:
            - name: COOKIE_SECRET
              value: {{ randAlphaNum 24 | quote }}
            - name: SECURE
              value: {{ .Values.launchpad.env.SECURE | quote }}
            - name: BASE_URL
              value: {{- include "launchpad.protocol" . }} ://{{- include "launchpad.host" . }}
            - name: STARDOG_INTERNAL_ENDPOINT
              value: {{- include "stardog.protocol" . }}://{{- include "stardog.host" . }}
            - name: STARDOG_EXTERNAL_ENDPOINT
              value: {{- include "stardog.protocol" . }}://{{- include "stardog.host" . }}
            - name: FRIENDLY_NAME
              value: {{ default "Stardog Applications" .Values.launchpad.env.FRIENDLY_NAME | quote }}
            - name: JWK_LOCATION
              value: {{ .Values.launchpad.env.JWK_LOCATION | quote }}
            - name: JWT_ISSUER
              value: {{ .Values.launchpad.env.JWT_ISSUER | quote }}
            - name: K8S_DEPLOYMENT
              value: {{ .Values.launchpad.env.K8S_DEPLOYMENT | quote }}
            - name: AZURE_AUTH_ENABLED
              value: {{ .Values.launchpad.env.AZURE_AUTH_ENABLED | quote }}
            - name: AZURE_CLIENT_ID
              value: {{ .Values.launchpad.env.AZURE_CLIENT_ID | quote }}
            - name: AZURE_CLIENT_SECRET
              value: {{ .Values.launchpad.env.AZURE_CLIENT_SECRET | quote }}
            - name: AZURE_CLIENT_PRIVATE_KEY_FILE
              value: {{ .Values.launchpad.env.AZURE_CLIENT_PRIVATE_KEY_FILE | quote }}
            - name: AZURE_CLIENT_CERTIFICATE_THUMBPRINT
              value: {{ .Values.launchpad.env.AZURE_CLIENT_CERTIFICATE_THUMBPRINT | quote }}
            - name: AZURE_CLIENT_CERTIFICATE_FILE
              value: {{ .Values.launchpad.env.AZURE_CLIENT_CERTIFICATE_FILE | quote }}
            - name: AZURE_TENANT
              value: {{ .Values.launchpad.env.AZURE_TENANT | quote }}
            - name: AZURE_AUTH_TOKEN_TYPE
              value: {{ .Values.launchpad.env.AZURE_AUTH_TOKEN_TYPE | quote }}
            - name: AZURE_STARDOG_SCOPE
              value: {{ .Values.launchpad.env.AZURE_STARDOG_SCOPE | quote }}
            - name: GOOGLE_AUTH_ENABLED
              value: {{ .Values.launchpad.env.GOOGLE_AUTH_ENABLED | quote }}
            - name: GOOGLE_CLIENT_ID
              value: {{ .Values.launchpad.env.GOOGLE_CLIENT_ID | quote }}
            - name: GOOGLE_CLIENT_SECRET
              value: {{ .Values.launchpad.env.GOOGLE_CLIENT_SECRET | quote }}
            - name: KEYCLOAK_AUTH_ENABLED
              value: {{ .Values.launchpad.env.KEYCLOAK_AUTH_ENABLED | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.launchpad.env.KEYCLOAK_CLIENT_ID | quote }}
            - name: KEYCLOAK_CLIENT_SECRET
              value: {{ .Values.launchpad.env.KEYCLOAK_CLIENT_SECRET | quote }}
            - name: KEYCLOAK_ENDPOINT
              value: {{ .Values.launchpad.env.KEYCLOAK_ENDPOINT | quote }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.launchpad.env.KEYCLOAK_REALM | quote }}
            - name: KEYCLOAK_TOKEN_ROLES_CLAIM
              value: {{ .Values.launchpad.env.KEYCLOAK_TOKEN_ROLES_CLAIM | quote }}
            - name: PASSWORD_AUTH_ENABLED
              value: {{ .Values.launchpad.env.PASSWORD_AUTH_ENABLED | quote }}
            - name: SESSION_EXPIRATION
              value: {{ .Values.launchpad.env.SESSION_EXPIRATION | quote }}
            - name: STARDOG_SERVER_CERT_PATH
              value: {{ .Values.launchpad.env.STARDOG_SERVER_CERT_PATH | quote }}
            - name: STARDOG_CLIENT_CERT_PATH
              value: {{ .Values.launchpad.env.STARDOG_CLIENT_CERT_PATH | quote }}
            - name: STARDOG_CLIENT_CERT_PRIVATE_KEY_PATH
              value: {{ .Values.launchpad.env.STARDOG_CLIENT_CERT_PRIVATE_KEY_PATH | quote }}
            {{/*
             Esto es un blucle key values
            {{- range $key, $evar := .Values.launchpad.env }}
            - name: {{ $key }}
              value: {{ $evar | quote }}
            {{- end }}
            {{- if .Values.jwt.enabled }}
            - name: JWK_LOCATION
              value: "/jwt"
            {{- end }}
            {{- range $.Values.env }} 
            - name: {{ .name }}
              value: {{ .value | quote}}
            {{- end }}
          */}}
          resources:
            {{- toYaml .Values.launchpad.resources | nindent 12 }}
{{/*        {{- if .Values.jwt.enabled }}
          volumeMounts:
          - name: {{ .Values.jwt.secretName }}
            mountPath: "/jwt/cert.key"  
            subPath: cert-key.key  
          - name: {{ .Values.jwt.secretName }}  
            mountPath: "/jwt/pubkey.pub" 
            subPath: public-key.pub
        {{- end }}  */}}
      {{- with .Values.launchpad.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.launchpad.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.launchpad.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{/*
  {{- if .Values.jwt.enabled }}
      volumes:
      - name: {{ .Values.jwt.secretName }}
        secret:
          secretName: {{ .Values.jwt.secretName }}
  {{- end }}
*/}}

{{- end }}
