{{- if .Values.launchpad.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stardog.fullname" . }}-launchpad
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app: {{ include "stardog.fullname" . }}-launchpad
  replicas: {{ .Values.launchpad.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "stardog.fullname" . }}-launchpad
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: server
        stardog.com/deployname: {{ .Release.Name }}-launchpad
        stardog.com/resource-type: stardog-apps
    spec:
      {{- if or .Values.launchpad.image.pullSecrets (and .Values.launchpad.image.username .Values.launchpad.image.password) }}
      imagePullSecrets:
      {{- if .Values.launchpad.image.pullSecrets }}
      {{- toYaml .Values.launchpad.image.pullSecrets | nindent 10 }}
      {{- end }}
      {{- if and .Values.launchpad.image.username .Values.launchpad.image.password }}
      - name: {{ .Release.Name }}-launchpad-image-pull-secret
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "launchpad.serviceAccountName" . }}
      initContainers:
      - name: generate-ssh-key
        image: alpine
        resources:
          requests:
            memory: 250Mi
            cpu: 300m
          limits:
            memory: 250Mi
            cpu: 300m
        command:
        - /bin/sh
        - -c
        - |
            apk add openssh;
            ssh-keygen -t rsa -m PEM -b 2048 -f /etc/ssh-keys/jwk/jwtRS256.key -N '';
            chmod 554 /etc/ssh-keys/jwk/jwtRS256.key*;
        volumeMounts:
          - name: ssh-key-jwk-vol
            mountPath: /etc/ssh-keys/jwk
      containers:
      - name: {{ .Chart.Name }}-launchpad
        image: "{{ .Values.launchpad.image.registry }}/{{ .Values.launchpad.image.repository }}:{{ .Values.launchpad.image.tag }}"
        imagePullPolicy: {{ .Values.launchpad.image.pullPolicy | quote }}
        securityContext:
        {{- toYaml .Values.stardog.securityContext | nindent 12 }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        {{- if .Values.launchpad.tls.internal.enabled }}
        volumeMounts:
        - name: jwk-vol
          mountPath: /jwk-old
          readOnly: true
        - name: ssh-key-jwk-vol
          mountPath: /jwk
          readOnly: true
        {{- end }}
        env:
          - name: COOKIE_SECRET
            value: {{ randAlphaNum 24 | quote }}
          - name: SECURE
            value: {{ .Values.launchpad.env.SECURE | quote }}
          - name: FRIENDLY_NAME
            value: {{ default "Stardog Applications" .Values.launchpad.env.FRIENDLY_NAME | quote }}
          - name: BASE_URL
            value: {{ printf "%s://%s " (include "launchpad.protocol" .) (include "launchpad.host" . ) }}
          - name: STARDOG_INTERNAL_ENDPOINT
            value: {{ printf "http://%s:%d" (include "stardog.fullname" .) (.Values.stardog.ports.server | int) }}
          - name: STARDOG_EXTERNAL_ENDPOINT
            value: {{ printf "%s://%s " (include "stardog.protocol" .) (include "stardog.host" . ) }} 
          {{- if or .Values.launchpad.env.JWK_LOCATION (gt (len .Values.launchpad.env.JWK_LOCATION) 0) }} 
          - name: JWK_LOCATION
            value: {{ .Values.launchpad.env.JWK_LOCATION | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.JWT_ISSUER (gt (len .Values.launchpad.env.JWT_ISSUER) 0) }}
          - name: JWT_ISSUER
            value: {{ .Values.launchpad.env.JWT_ISSUER | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.K8S_DEPLOYMENT (gt (len .Values.launchpad.env.K8S_DEPLOYMENT) 0) }}
          - name: K8S_DEPLOYMENT
            value: {{ .Values.launchpad.env.K8S_DEPLOYMENT | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.AZURE_AUTH_ENABLED (gt (len .Values.launchpad.env.AZURE_AUTH_ENABLED) 0) }}
          - name: AZURE_AUTH_ENABLED
            value: {{ .Values.launchpad.env.AZURE_AUTH_ENABLED | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.AZURE_CLIENT_ID (gt (len .Values.launchpad.env.AZURE_CLIENT_ID) 0) }}
          - name: AZURE_CLIENT_ID
            value: {{ .Values.launchpad.env.AZURE_CLIENT_ID | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.AZURE_CLIENT_SECRET (gt (len .Values.launchpad.env.AZURE_CLIENT_SECRET) 0) }}
          - name: AZURE_CLIENT_SECRET
            value: {{ .Values.launchpad.env.AZURE_CLIENT_SECRET | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.AZURE_CLIENT_PRIVATE_KEY_FILE (gt (len .Values.launchpad.env.AZURE_CLIENT_PRIVATE_KEY_FILE) 0) }}
          - name: AZURE_CLIENT_PRIVATE_KEY_FILE
            value: {{ .Values.launchpad.env.AZURE_CLIENT_PRIVATE_KEY_FILE | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.AZURE_CLIENT_CERTIFICATE_THUMBPRINT (gt (len .Values.launchpad.env.AZURE_CLIENT_CERTIFICATE_THUMBPRINT) 0) }}
          - name: AZURE_CLIENT_CERTIFICATE_THUMBPRINT
            value: {{ .Values.launchpad.env.AZURE_CLIENT_CERTIFICATE_THUMBPRINT | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.AZURE_CLIENT_CERTIFICATE_FILE (gt (len .Values.launchpad.env.AZURE_CLIENT_CERTIFICATE_FILE) 0) }}
          - name: AZURE_CLIENT_CERTIFICATE_FILE
            value: {{ .Values.launchpad.env.AZURE_CLIENT_CERTIFICATE_FILE | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.AZURE_TENANT (gt (len .Values.launchpad.env.AZURE_TENANT) 0) }}
          - name: AZURE_TENANT
            value: {{ .Values.launchpad.env.AZURE_TENANT | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.AZURE_AUTH_TOKEN_TYPE (gt (len .Values.launchpad.env.AZURE_AUTH_TOKEN_TYPE) 0) }}
          - name: AZURE_AUTH_TOKEN_TYPE
            value: {{ .Values.launchpad.env.AZURE_AUTH_TOKEN_TYPE | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.AZURE_STARDOG_SCOPE (gt (len .Values.launchpad.env.AZURE_STARDOG_SCOPE) 0) }}
          - name: AZURE_STARDOG_SCOPE
            value: {{ .Values.launchpad.env.AZURE_STARDOG_SCOPE | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.GOOGLE_AUTH_ENABLED (gt (len .Values.launchpad.env.GOOGLE_AUTH_ENABLED) 0) }}
          - name: GOOGLE_AUTH_ENABLED
            value: {{ .Values.launchpad.env.GOOGLE_AUTH_ENABLED | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.GOOGLE_CLIENT_ID (gt (len .Values.launchpad.env.GOOGLE_CLIENT_ID) 0) }}
          - name: GOOGLE_CLIENT_ID
            value: {{ .Values.launchpad.env.GOOGLE_CLIENT_ID | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.GOOGLE_CLIENT_SECRET (gt (len .Values.launchpad.env.GOOGLE_CLIENT_SECRET) 0) }}
          - name: GOOGLE_CLIENT_SECRET
            value: {{ .Values.launchpad.env.GOOGLE_CLIENT_SECRET | quote }}
          {{- end }}
          {{- if or  .Values.launchpad.env.KEYCLOAK_AUTH_ENABLED (gt (len .Values.launchpad.env.KEYCLOAK_AUTH_ENABLED) 0) }}
          - name: KEYCLOAK_AUTH_ENABLED
            value: {{ .Values.launchpad.env.KEYCLOAK_AUTH_ENABLED | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.KEYCLOAK_CLIENT_ID (gt (len .Values.launchpad.env.KEYCLOAK_CLIENT_ID) 0) }}
          - name: KEYCLOAK_CLIENT_ID
            value: {{ .Values.launchpad.env.KEYCLOAK_CLIENT_ID | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.KEYCLOAK_CLIENT_SECRET (gt (len .Values.launchpad.env.KEYCLOAK_CLIENT_SECRET) 0) }}
          - name: KEYCLOAK_CLIENT_SECRET
            value: {{ .Values.launchpad.env.KEYCLOAK_CLIENT_SECRET | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.KEYCLOAK_ENDPOINT (gt (len .Values.launchpad.env.KEYCLOAK_ENDPOINT) 0) }}
          - name: KEYCLOAK_ENDPOINT
            value: {{ .Values.launchpad.env.KEYCLOAK_ENDPOINT | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.KEYCLOAK_REALM (gt (len .Values.launchpad.env.KEYCLOAK_REALM) 0) }}
          - name: KEYCLOAK_REALM
            value: {{ .Values.launchpad.env.KEYCLOAK_REALM | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.KEYCLOAK_TOKEN_ROLES_CLAIM (gt (len .Values.launchpad.env.KEYCLOAK_TOKEN_ROLES_CLAIM) 0) }}
          - name: KEYCLOAK_TOKEN_ROLES_CLAIM
            value: {{ .Values.launchpad.env.KEYCLOAK_TOKEN_ROLES_CLAIM | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.PASSWORD_AUTH_ENABLED (gt (len .Values.launchpad.env.PASSWORD_AUTH_ENABLED) 0) }}
          - name: PASSWORD_AUTH_ENABLED
            value: {{ .Values.launchpad.env.PASSWORD_AUTH_ENABLED | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.SESSION_EXPIRATION (gt (len .Values.launchpad.env.SESSION_EXPIRATION) 0) }}
          - name: SESSION_EXPIRATION
            value: {{ .Values.launchpad.env.SESSION_EXPIRATION | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.STARDOG_SERVER_CERT_PATH (gt (len .Values.launchpad.env.STARDOG_SERVER_CERT_PATH) 0) }}
          - name: STARDOG_SERVER_CERT_PATH
            value: {{ .Values.launchpad.env.STARDOG_SERVER_CERT_PATH | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.STARDOG_CLIENT_CERT_PATH (gt (len .Values.launchpad.env.STARDOG_CLIENT_CERT_PATH) 0) }}
          - name: STARDOG_CLIENT_CERT_PATH
            value: {{ .Values.launchpad.env.STARDOG_CLIENT_CERT_PATH | quote }}
          {{- end }}
          {{- if or .Values.launchpad.env.STARDOG_CLIENT_CERT_PRIVATE_KEY_PATH (gt (len .Values.launchpad.env.STARDOG_CLIENT_CERT_PRIVATE_KEY_PATH) 0) }}
          - name: STARDOG_CLIENT_CERT_PRIVATE_KEY_PATH
            value: {{ .Values.launchpad.env.STARDOG_CLIENT_CERT_PRIVATE_KEY_PATH | quote }}
          {{- end }}
        resources:
{{- toYaml .Values.launchpad.resources | nindent 12 }}
{{- if .Values.launchpad.tls.internal.enabled }}
      volumes:
        - name: ssh-key-jwk-vol
          emptyDir: {}
        - name: jwk-vol
          secret:
            secretName: {{ .Values.launchpad.tls.internal.secretName }}
{{- end }}
      {{- with .Values.launchpad.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.launchpad.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.launchpad.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
      {{- end }}

{{- end -}}

