{{- if .Values.stardog.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "stardog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "stardog.fullname" . }}
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      securityContext:
        {{- toYaml .Values.stardog.securityContext | nindent 8 }}
      restartPolicy: Never
      containers:
      - name: post-install-job
        imagePullPolicy: {{ .Values.stardog.image.pullPolicy }}
        image: {{ .Values.stardog.image.registry }}/{{ .Values.stardog.image.repository }}:{{ .Values.stardog.image.tag }}
        volumeMounts:
        - name: {{ include "stardog.fullname" . }}-password
          mountPath: /etc/stardog-password
          readOnly: true
        resources:
          requests:
            memory: 250Mi
            cpu: 300m
          limits:
            memory: 250Mi
            cpu: 300m
        env:
        - name: PORT
          value: "{{ .Values.stardog.ports.server }}"
        - name: HOST
          value: "{{ include "stardog.fullname" . }}.{{ .Release.Namespace }}"
        - name: PROTOCOL
        {{ if .Values.stardog.ssl.enabled }}
          value: "https"
        {{ else }}
          value: "http"
        {{- end }}
        command:
        - /bin/bash
        - -c
        - |
          set -ex
          {{ .Files.Get "files/utils.sh" | indent 10 }}
          wait_for_start ${HOST} ${PORT} ${PROTOCOL}
          change_pw ${HOST} ${PORT} ${PROTOCOL}
      {{- with .Values.stardog.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and .Values.stardog.image.username .Values.stardog.image.password }}
      imagePullSecrets:
          - name: {{ .Release.Name }}-image-pull-secret
      {{- end }}
      volumes:
      - name: {{ include "stardog.fullname" . }}-password
        secret:
          secretName: {{ include "stardog.fullname" . }}-password
          items:
            - key: password
              path: adminpw
              mode: 444
{{- end }}