{{- if .Values.launchpad.enabled }}
{{- if .Values.launchpad.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "launchpad.serviceAccountName" . }}
  labels:
    app: {{ include "stardog.fullname" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: server
    stardog.com/deployname: {{ .Release.Name }} 
  {{- with .Values.launchpad.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
