{{- if .Values.stardog.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stardog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "stardog.fullname" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- with .Values.stardog.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.stardog.ports.server }}
    name: server
  {{- if .Values.stardog.ports.sql }}
  - port: {{ .Values.stardog.ports.sql }}
    name: sql
  {{- end }}
  type: {{ .Values.stardog.service.type }}
  {{- if .Values.stardog.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.stardog.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ include "stardog.fullname" . }}
{{- end }}
---
{{ if .Values.launchpad.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stardog.fullname" . }}-launchpad
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "stardog.fullname" . }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- with .Values.stardog.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.launchpad.service.port }}
  type: {{ .Values.launchpad.service.type }}
  {{- if .Values.launchpad.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.launchpad.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ include "stardog.fullname" . }}-launchpad
{{ end }}
